production:
  clients:
    default:
      uri: mongodb://laconic:l23785614c@ds015478.mongolab.com:15478/heroku_b296vwrl
      options:
        connect_timeout: 15
  options:

development:
  clients:
    default:
      uri: mongodb://laconic:l23785614c@ds015478.mongolab.com:15478/heroku_b296vwrl
      options:
        connect_timeout: 15
  options:

test:
  clients:
    default:
      database: files_test_test
      hosts:
        - localhost:27017
      options:



